# Generated by Django 3.1 on 2020-11-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20201125_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='topici',
        ),
    ]
